### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by wmertens** [sr229/wsl-systemd#1]
Hi,

I wonder if you can replace the dependency on deamonize by running the command with stdin closed and backgrounded: `...systemd... <&- &`

I believe bash will behave similiar to daemonize then.

You could also combine the grep+awk into just awk with `'/regex/ && !/regex/ {print $2}'`

On mobile, sorry

**Comment by sr229** [comment]
That's rather interesting, I've never thought of that. Let me see what I can do so we don't need to run daemonize to run systemd in a namespace.

**Comment by sr229** [comment]
Should be fulfilled now, all you need is `util-linux` from now on.
